commit_message: '[L10N]: New translations %original_file_name% from Crowdin [ci skip]'
append_commit_message: false
base_path: /Resources/Private/Language
files:
  - source: '/*.xlf'
    ignore:
      - '/%two_letters_code%.%original_file_name%'
    translation: '/%two_letters_code%.%original_file_name%'
