services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\CodeHighlight\:
    resource: '../Classes/*'

  Brotkrueml\CodeHighlight\DataProcessing\FlexFormProcessor:
    public: true

  Brotkrueml\CodeHighlight\Hooks\PageLayoutView\ContentElementPreviewRenderer:
    public: true

  Brotkrueml\CodeHighlight\Service\ProgrammingLanguages:
    public: true
