services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\CodeHighlight\:
    resource: '../Classes/*'

  Brotkrueml\CodeHighlight\Service\ProgrammingLanguages:
    public: true
